#!/usr/bin/env python
import subprocess, os, multiprocessing, signal, sys, time
from app.utils import get_logger
import uvicorn

logger = get_logger(__name__)

from fastapi import FastAPI

app = FastAPI()


@app.get("/")
def root():
    return {"message": "Hello World"}

def main():
  logger.info('Serve script executing...')

if __name__ == '__main__':
  uvicorn.run(app, port="8080", host="0.0.0.0")